language: python
sudo: false
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
addons:
  apt:
    packages:
    - libgmp-dev
install:
  - pip install --install-option="--no-cython-compile" Cython
  - "pip install Sphinx"
  - "pip install nose"
  - "pip install ."
script:
  - "nosetests"
  - "cd docs"
  - "make doctest"
