language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libgmp-dev"
install:
  - "pip install Cython"
  - "pip install Sphinx"
  - "pip install ."
script:
  - "cd docs"
  - "make doctest"

