language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libgmp-dev"
install:
  - "pip install Cython"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'Jinja2<2.7'; fi" # Jinja2 2.6 is last version which supports Python 3.2; required by Sphinx
  - "pip install Sphinx"
  - "pip install ."
script:
  - "cd docs"
  - "make doctest"

