language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libgmp-dev"
install:
  - "pip install Cython --use-mirrors"
  - "pip install Sphinx --use-mirrors"
  - "pip install . --use-mirrors"
script:
  - "cd docs"
  - "make doctest"

